# Strategy Simulation for Random Matrices
Here we run a code where we initiailise a Matrix and then check both strategies work

In [26]:
import numpy as np

def simulate_game(n):
    # Initialize an n x n matrix with -1 to represent an empty cell
    matrix = np.full((n, n), -1)

    # Function to check if placing '0' in (i, j) will make the determinant zero
    def will_det_be_zero(i, j):
        matrix_copy = np.where(matrix == -1, 0, matrix)  # Replace -1 with 0 for determinant calculation
        matrix_copy[i, j] = 0
        return np.isclose(np.linalg.det(matrix_copy), 0)

    # Function to perform a move for player 1 (place a 1) or player 0 (place a 0)
    def make_move(player, position):
        matrix[position] = player

    # Simulate the game
    for move in range(n * n):
        player = move % 2
        empty_cells = np.argwhere(matrix == -1)
        if empty_cells.size > 0:
            if player == 1:
                # Player 1 places a 1 in a random empty cell
                random_cell = empty_cells[np.random.choice(empty_cells.shape[0])]
                make_move(1, random_cell)
            else:
                # For n >= 4, apply the reflection strategy
                if n >= 4:
                    move_made = False
                    for i in range(n):
                        for j in range(n // 2):
                            if matrix[i, j] == 1 and matrix[i, n - j - 1] == -1:
                                make_move(0, (i, n - j - 1))
                                move_made = True
                                break
                        if move_made:
                            break
                    if not move_made:
                        # If no reflection move was made, place a 0 in a cell that will make det zero
                        for cell in empty_cells:
                            if will_det_be_zero(*cell):
                                make_move(0, cell)
                                break
                else:
                    # For n < 4, place a 0 in a cell that will make det zero
                    for cell in empty_cells:
                        if will_det_be_zero(*cell):
                            make_move(0, cell)
                            break

    # Check if the final matrix has a determinant of zero
    det = np.linalg.det(np.where(matrix == -1, 0, matrix)) if -1 not in matrix else None
    return matrix, np.isclose(det, 0)

# Simulate the game for n=3 and n=4
results_n3 = simulate_game(3)
results_n4 = simulate_game(4)

print("Simulation for n=3:")
print(results_n3[0])
print("Determinant is zero:", results_n3[1])

print("\nSimulation for n=4:")
print(results_n4[0])
print("Determinant is zero:", results_n4[1])


Simulation for n=3:
[[0 0 0]
 [0 0 0]
 [1 1 1]]
Determinant is zero: True

Simulation for n=4:
[[0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]]
Determinant is zero: True
